### PR TITLE
[✨ New feature: API] Github Authentication using Passport

### PR DESCRIPTION
**Pull request by afif1400**
## Description

Have added Github strategy got authentication using GitHub and added a jwt strategy that can be used as a common jwt authentication middleware.

### CODE REVIEW

**Comment by naganevsachin** [comment]
@afif1400 follow the PR format. The title wasn't following it, for now, I have corrected it.

**Comment by afif1400** [comment]
> @afif1400 follow the PR format. The title wasn't following it, for now, I have corrected it.

okay, I'll follow that.

**Comment by afif1400** [comment]
> @afif1400 follow the PR format. The title wasn't following it, for now, I have corrected it.

okay, I'll follow that.

**Review by naganevsachin — COMMENTED** [review]
@afif1400 you haven't integrated the feature into the route. Please do check on it

**Comment by afif1400** [comment]
> @afif1400 you haven't integrated the feature into the route. Please do check on it

Yeah.... before doing that, shall I follow the pattern that you have implemented for authentication or shall I seperate github and also check the code, let me know if I should contain.

**Comment by naganevsachin** [comment]
> 
> 
> > @afif1400 you haven't integrated the feature into the route. Please do check on it
> 
> Yeah.... before doing that, shall I follow the pattern that you have implemented for authentication or shall I seperate github and also check the code, let me know if I should contain.

Yes @afif1400 follow the pattern in which it is presently implemaneted in the signup and login route  that would be great.

**Comment by naganevsachin** [comment]
Hye, @afif1400 any progress

**Pull request closed without merging**
